export const DEFAULT_FOCUS_DURATION_MINUTES = 25;
export const DEFAULT_SHORT_BREAK_DURATION_MINUTES = 5;
export const DEFAULT_LONG_BREAK_DURATION_MINUTES = 15;
export const FOCUS_SESSIONS_PER_LONG_BREAK = 4;
export const STUDY_CYCLE_IDLE_RESET_MINUTES = 120;
